### ISSUE TITLE
Issue with machine code generation in Mac

### ISSUE THREAD

**Issue by KY31** [Cryptolens/cryptolens-python#15]
When i call Helpers.GetMachineCode() in Mac, it returns 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/licensing/methods.py", line 137, in GetMachineCode
    res = HelperMethods.start_process(["system_profiler","SPHardwareDataType"]).decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'

**Comment by artemlos** [comment]
@KY31 Thanks for reporting this issue. It is now fixed in https://github.com/Cryptolens/cryptolens-python/commit/2107ab4dd7c12ac1eb43c039bacf6af6cf225350 and available in the latest release (v12).
