### ISSUE TITLE
TypeError when handling error message if not connected to internet

### ISSUE THREAD

**Issue by jamiesandenr** [Cryptolens/cryptolens-python#21]
Windows 10 Pro
Python 3.7.6
`licensing` v. 0.17

### To reproduce
When *not* connected to the internet:
```
from licensing.methods import Key
# set TOKEN, KEY, MACHINE_CODE, PRODUCT_ID appropriately
success, response = Key.deactivate(TOKEN, PRODUCT_ID, KEY, MACHINE_CODE)
```
### Expected result
No unhandled exception
`success == False`, `response` is an error message (`str`)

### Output
```
Traceback (most recent call last):
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 1319, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 966, in send
    self.connect()
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1414, in connect
    super().connect()
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 938, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python37\lib\socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python37\lib\socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\<user>\envs\<env>\lib\site-packages\licensing\methods.py", line 163, in deactivate
    "MachineCode":machine_code})
  File "C:\Users\<user>\envs\<env>\lib\site-packages\licensing\internal.py", line 104, in send_request
    .encode("utf-8")).read().decode("utf-8")
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 1362, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 1321, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 11001] getaddrinfo failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\<user>\envs\<env>\lib\site-packages\licensing\methods.py", line 167, in deactivate
    return (None, "Could not contact the server. Error message: " + e.reason)
TypeError: can only concatenate str (not "gaierror") to str
```

**Comment by artemlos** [comment]
@jamiesandenr thanks for reporting the error! We will release a fix later today 👍

**Comment by artemlos** [comment]
@jamiesandenr The error should now be fixed.

**Comment by jamiesandenr** [comment]
Thank you!
